### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/jasmine#1]
不要弄成点击下一页加载，弄成触底加载。章节，漫画

**Comment by niuhuan** [comment]
> 不要弄成点击下一页加载，弄成触底加载。章节，漫画

你可以点一下右上角的三条横线，换成流式，默认设计是流式，估计发布之前把默认值搞错了。

**Comment by niuhuan** [comment]
我发现有的图切图正确，有的图切图错误，不知道怎么搞的

**Comment by Minori-ty** [comment]
太肝了，等7月份我忙完自己的时候再看能不能学一下flutter一起维护一下
