### ISSUE TITLE
漫画的下载目录

### ISSUE THREAD

**Issue by Salomens** [niuhuan/jasmine#10]
请问下载下来的漫画的文件在哪个目录

**Comment by niuhuan** [comment]
> 请问下载下来的漫画的文件在哪个目录

在程序目录里，下载完之后可以离线阅读，导出的功能还没有完成。

**Comment by Salomens** [comment]
> 

感谢解答！

**Comment by niuhuan** [comment]
/data/data/niuhuan.jasmine/

**Comment by buyu0407** [comment]
> /data/data/niuhuan.jasmine/

好吧，是需要root才能看得到了。。

**Comment by hanqqp** [comment]
后继会有下载的导出吗？？求

**Comment by niuhuan** [comment]
> 后继会有下载的导出吗？？求

在计划里, pikapika导入导出一样的功能, 维护的项目太多, 暂时没码这个, 时间不好说。

**Comment by hanqqp** [comment]
> > 后继会有下载的导出吗？？
> 
> 里，皮卡皮卡导入计划导出一样的功能，维护的项目中，暂时没码这个，时间不好说。

好的好的，感谢,,Ծ^Ծ,,

**Comment by niuhuan** [comment]
@hanqqp 

如果您比较急，懂rust和flutter可以PR源代码。

**Comment by hanqqp** [comment]
> @hanqqp
> 
> 如果您比较急代码，了解rust和flutter可以PR源。

好的，那我试试(≧ω≦)，学过C++，有空试试，嘻嘻(♡˙︶˙♡)

**Comment by 872035804** [comment]
要怎么发电？
