### ISSUE TITLE
最近无法打开，只显示“被玩坏”

### ISSUE THREAD

**Issue by wscyyy** [niuhuan/jasmine#100]
今天上午10：30分左右JM该软件打不开了，并显示“被玩坏”前几天还没问题，也试过了VPN但并无作用，请大大修复一下服务器，谢谢辣！！

**Comment by niuhuan** [comment]
我也修复不了啦 安静等一段时间吧

**Comment by wscyyy** [comment]
您也发现问题也解决不了嘛？好叭，那也谢谢您(´இωஇ｀)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] 最近无法打开，只显示“被玩坏” (Issue #100)




 
我也修复不了啦 安静等一段时间吧

**Comment by a2504206417** [comment]
我还以为只是我的问题，原来是服务器，等大大修复了(˃ ⌑ ˂ഃ )

**Comment by wscyyy** [comment]
只能这样了，呜呜呜≥﹏≤



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午1:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] 最近无法打开，只显示“被玩坏” (Issue #100)




 
我还以为只是我的问题，原来是服务器，等大大修复了(˃ ⌑ ˂ഃ )

**Comment by 15216493775** [comment]
我还以为看不了

**Comment by wscyyy** [comment]
果然都一样啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 下午5:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] 最近无法打开，只显示“被玩坏” (Issue #100)




 
我还以为看不了

**Comment by ParanoiaIsGreat** [comment]
> 我也修复不了啦 安静等一段时间吧

不太懂，大概是作者大大用的分流挂了？隔壁某软件可以正常浏览

![image](https://github.com/niuhuan/jasmine/assets/10475153/0f7c7d05-fdec-4a04-90db-b30bc12978ee)

**Comment by wscyyy** [comment]
好叭，那就只能先等等了，希望大大能早点发现问题并解决，感谢呜呜呜≥﹏≤



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 晚上10:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] 最近无法打开，只显示“被玩坏” (Issue #100)




  
我也修复不了啦 安静等一段时间吧
  
不太懂，大概是作者大大用的分流挂了？隔壁某软件可以正常浏览

**Comment by niuhuan** [comment]
确认是最新版，然后用右上角的菜单切换分流

**Comment by wscyyy** [comment]
谢谢，谢谢，问题已解决感谢大佬≡ω≡



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 上午10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] 最近无法打开，只显示“被玩坏” (Issue #100)




 
确认是最新版，然后用右上角的菜单切换分流

**Comment by wscyyy** [comment]
哥，又发现新问题了，就是，有一些打不开，而且还有一些打的开，但是全都是同一个本子，每一个能打开的都是同一个本子（那个同一个本子就是JM娘的AI画）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 上午10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] 最近无法打开，只显示“被玩坏” (Issue #100)




 
确认是最新版，然后用右上角的菜单切换分流
