### ISSUE TITLE
ios.1.5.1 显示被玩坏

### ISSUE THREAD

**Issue by wer33445** [niuhuan/jasmine#102]
ios 最新版 151打开显示被玩坏

**Comment by 15216493775** [comment]
我都不知道咋下载，难受

**Comment by hugolubingshen** [comment]
安卓版一样

**Comment by xiayahan** [comment]
打不开，显示玩坏

**Comment by wscyyy** [comment]
在右上角切换分流（右上角的三条杠，然后下面第一行，第二个的分页换一下就OK了）

**Comment by wscyyy** [comment]
完了，刚刚试了一下，发现有点小问题，就是，都变成同一个本子了，每一个都是同一个本子(;∀;)

**Comment by hugolubingshen** [comment]
啥叫全都成了一个本子？我看是目录都缩起来了

**Comment by wscyyy** [comment]
就是不管打开哪个都是同一个本子，没有区别(T^T)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] ios.1.5.1 显示被玩坏 (Issue #102)




 
啥叫全都成了一个本子？我看是目录都缩起来了

**Comment by xiayahan** [comment]
每一个都是同一个本子

**Comment by yhhfdsxg** [comment]
不仅锁了国区，还bug上了

**Comment by wscyyy** [comment]
是的，呜呜呜



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月28日(周六) 下午4:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/jasmine] ios.1.5.1 显示被玩坏 (Issue #102)




 
不仅锁了国区，还bug上了

**Comment by xiayahan** [comment]
还是有本子显示的是同一个ai画的
