### ISSUE TITLE
现在能进入，但漫画点进去都是同一个本

### ISSUE THREAD

**Issue by a2504206417** [niuhuan/jasmine#104]

**Comment by h1810747529** [comment]
同情况

**Comment by h1810747529** [comment]
![Screenshot_2023-10-27-10-48-51-235_opensource.jasmine.jpg](https://github.com/niuhuan/jasmine/assets/105938991/f45c0b20-ffdd-4da3-b21b-8b4881b2af4f)

![Screenshot_2023-10-27-10-48-56-920_opensource.jasmine.jpg](https://github.com/niuhuan/jasmine/assets/105938991/fcc6370c-919b-445e-9249-9af1869bb352)

![Screenshot_2023-10-27-10-49-02-612_opensource.jasmine.jpg](https://github.com/niuhuan/jasmine/assets/105938991/324e9390-1cfb-4943-902b-290d09c6e27a)

**Comment by niuhuan** [comment]
好的

**Comment by h1810747529** [comment]
![IMG_20231027_105139.jpg](https://github.com/niuhuan/jasmine/assets/105938991/e4fffbde-875b-4236-a34e-1a1d84db95ae)

**Comment by 15216493775** [comment]
兄弟们，谁能告诉我安卓最新版下载步骤有哪些啊

**Comment by 18143418696** [comment]
一样的看不了，作者也没有说明一下

**Comment by 18143418696** [comment]
> ![IMG_20231027_105139.jpg](https://github.com/niuhuan/jasmine/assets/105938991/e4fffbde-875b-4236-a34e-1a1d84db95ae)
> 
> 

一样啊，不什么情况

**Comment by 18143418696** [comment]
> 好的

作者，这个怎么回事，看不了了

**Comment by niuhuan** [comment]
散了吧，如果能修好会发布新版本，暂时用github.com/niuhuan/pikapika吧

**Comment by asdijiwww** [comment]
我也是这个问题，请问这是怎么回事啊

**Comment by WX-BD** [comment]
> 散了吧，如果能修好会发布新版本，暂时用pikapika吧
服务器炸了吗

**Comment by a2504206417** [comment]
感谢作者连夜写代码的更新，新版本可以正常看了，感谢(◦˙▽˙◦)

**Comment by meme999n** [comment]
> 感谢作者连夜写代码的更新，新版本可以正常看了，感谢(◦˙▽˙◦)

还是不能用啊

**Comment by a2504206417** [comment]
> > 感谢作者连夜写代码的更新，新版本可以正常阅读，谢谢(°˙▽˙°)
> 
> 还是不能用啊

我下载新版本就可以了

**Comment by a2504206417** [comment]
还没完全修复，部分本子还是禁漫娘

**Comment by zombie1912** [comment]
部分本子里会爆出禁漫娘

**Comment by niuhuan** [comment]
没搞懂, 我感觉好像全是金曼娘

**Comment by zombie1912** [comment]
有的本子里有几话是正常的,有几话是禁漫娘

**Comment by choualvin** [comment]
还是不对
