### ISSUE TITLE
怎么删除单个本子,只找到全删的按钮

### ISSUE THREAD

**Issue by zombie1912** [niuhuan/jasmine#115]

**Comment by niuhuan** [comment]
软件恢复正常才会维护,现在不确定能不能继续用下去

**Comment by zombie1912** [comment]
@niuhuan 群在哪里可以加，主页哪个点不进去

**Comment by niuhuan** [comment]
> @niuhuan 群在哪里可以加，主页哪个点不进去

下载页

**Comment by zombie1912** [comment]
我在下载页发电下面那个群聊链接进的,不行,要科学上网吗?

**Comment by niuhuan** [comment]
如果你在禁止使用Telegram的地区,是需要代理的

> 我在下载页发电下面那个群聊链接进的,不行,要科学上网吗?
