### ISSUE TITLE
PC端鼠标滚轮的问题

### ISSUE THREAD

**Issue by mx41shy** [niuhuan/jasmine#12]
作者您好：
        PC端鼠标滚轮滚动距离很短，翻页很费力，有没有可以改变滚轮滚动距离的设定？

**Comment by niuhuan** [comment]
现在还不支持。可以用键盘，但是只支持按页翻动。或者是用鼠标拖动。

**Comment by mx41shy** [comment]
> 现在还不支持。可以用键盘，但是只支持按页翻动。或者是用鼠标拖动。

好吧。（Sad）
