### ISSUE TITLE
1.5.4显示被玩坏

### ISSUE THREAD

**Issue by ws11451** [niuhuan/jasmine#121]
更新的1.5.4显示被玩坏

**Comment by 1127664922** [comment]
网络问题

**Comment by byzxxsyyz** [comment]
更新1.5.4后我也显示被玩坏

**Comment by hugolubingshen** [comment]
没玩坏，但是登录不了，翻不翻墙都一样

**Comment by ruchuby** [comment]
因为没过cloudflare人机验证，爬不到数据？@niuhuan

**Comment by fuckingPZY** [comment]
@niuhuan 显示被玩坏

**Comment by fuckingPZY** [comment]
> 没玩坏，但是登录不了，翻不翻墙都一样

真的吗？为什么我的是玩坏

**Comment by niuhuan** [comment]
打开是计算器, 说明之前的版本并没有好好看说明, 或者是新用户

提示 < 不能解析, 属于网络问题, 没有选分流, 或者当地, 再或者梯子的地区不能使用接口。

`接口加了验证, 认为不是官方客户端就会返回jm娘, 这个才是最近在解决的问题`

**Comment by hugolubingshen** [comment]
> 打开是计算器, 说明之前的版本并没有好好看说明, 或者是新用户
> 
> 提示 < 不能解析, 属于网络问题, 没有选分流, 或者当地, 再或者梯子的地区不能使用接口。
> 
> `接口加了验证, 认为不是官方客户端就会返回jm娘, 这个才是最近在解决的问题`

选了分流，Api分流4个一直能请求到，图片分流选的随机，梯子换了好几个国家，也是玩坏了，请给个最优配置

**Comment by hugolubingshen** [comment]
已经更新到1.5.5

**Comment by niuhuan** [comment]
您可以去 https://github.com/niuhuan/jenny/releases

据说 0.2.1 分流有的是好的

网络的问题说不准

**Comment by niuhuan** [comment]
我不管啥版本都是jm娘，我已经放弃了
