### ISSUE TITLE
1.6.1版本仍然存在点进去之后显示统一ai版jm娘本子的问题

### ISSUE THREAD

**Issue by heathen233333** [niuhuan/jasmine#125]
1.6.1版本仍然有不少本子点进去之后显示同一ai画风的jm娘本子，恳求作者大佬解决，谢谢！

**Comment by hugolubingshen** [comment]
确实，早上还好好的，下午又全成了jm

**Comment by xiayahan** [comment]
确实

**Comment by wuqianhuan** [comment]
我求你了，把那个本子的源给删了，你就是一直导向别的本子都行，从1.5开始一直是这破事

**Comment by 1-uuuuuuuuu** [comment]
确实是的

**Comment by niuhuan** [comment]
我们只是个第三方客户端开源项目，主站在维护这些漫画，目前修复不了，如果觉得不好用可以用其他软件。
