### ISSUE TITLE
不能登录，一直提示登录失败

### ISSUE THREAD

**Issue by inSANITYxxxx** [niuhuan/jasmine#128]
账号和邮箱都试了，一直提示登录失败，禁漫原版软件就能正常登上去

**Comment by niuhuan** [comment]
客户端API已经不能用了,新的WebAPI软件在写了,但是需要很久

**Comment by inSANITYxxxx** [comment]
好的大佬，明白了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月12日 17:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [niuhuan/jasmine] 不能登录，一直提示登录失败 (Issue #128) |

客户端API已经不能用了,新的WebAPI软件在写了,但是需要很久

**Comment by 13694835138** [comment]
如何更新

**Comment by 13694835138** [comment]
如何更新

**Comment by 13694835138** [comment]
下载地址是什么

**Comment by 13694835138** [comment]
我也是账号和邮箱都试了，一直提示登录失败，禁漫原版软件就能正常登上去，现在好了吗？

**Comment by niuhuan** [comment]
已经不能用了，已经说了很多次可
