### ISSUE TITLE
开发请求

### ISSUE THREAD

**Issue by HiRA017** [niuhuan/jasmine#13]
作者有可能再开坑新的阅读器吗？

您的app都十分美观易用，不知您是否有兴趣开发 漫画柜 的阅读器呢？

有在GitHub上发现过他人所开发之app，不过貌似停更太久时常会出现连接错误。（请参考→https://github.com/Aoi-hosizora/manhuagui_flutter ）

多有打扰，致以敬意。

**Comment by niuhuan** [comment]
仓库里的域名打不开,  可能是服务的原因吧。

**Comment by HiRA017** [comment]
> 仓库里的域名打不开, 可能是服务的原因吧。

该漫画网站（manhuagui.com）似乎屏蔽了大陆 IP 的访问，但使用 VPN、甚至对应港澳节点全局连接时，此 app（https://github.com/Aoi-hosizora/manhuagui_flutter/）也会出现 time out 等错误，即使这个时候用浏览器打开网址可以正常访问。

猜测是 API 需要更新。

**Comment by niuhuan** [comment]
我用了科学上网也打不开, 试了几个节点。

**Comment by HiRA017** [comment]
> 我用了科学上网也打不开, 试了几个节点。

问题突然变得玄学起来了🤔
