### ISSUE TITLE
怎么注册

### ISSUE THREAD

**Issue by dove1417** [niuhuan/jasmine#134]

**Comment by dove1417** [comment]
![Screenshot_20240430_203219_opensource jasmine](https://github.com/niuhuan/jasmine/assets/158533673/457a01e9-0597-4368-8e31-701d8486c609)
为什么有这

**Comment by dove1417** [comment]
> 去电子邮件里点一下链接

哪个邮箱，注册天堂的那个？

**Comment by dove1417** [comment]
> 去电子邮件里点一下链接

忘了是哪个邮箱了怎么办

**Comment by niuhuan** [comment]
再注册一个
