### ISSUE TITLE
如何完整卸载早期版本

### ISSUE THREAD

**Issue by 13br0t7** [niuhuan/jasmine#137]
iOS15.1版本下使用trollstore安装使用了jasmine 1.4.1版本。
现在改用最新版了，请问如何完整删除旧版本的缓存？是否仅删除app本体即可？还是需要进入相关目录手动删除，能否提供缓存目录，谢谢！

**Comment by niuhuan** [comment]
正常iOS只要删除app即可， 没用过 trollstore。也可以在应用程序菜单里清除缓存
