### ISSUE TITLE
兑换码发电出现FALL

### ISSUE THREAD

**Issue by cwt2003** [niuhuan/jasmine#138]
在爱发电中购买后无法在jasmine中通过“我刚才发电了”进行兑换，更换发电方式也不行，一直出现FALL

**Comment by niuhuan** [comment]
你先进群（需要科学上网）  https://t.me/+7EyAiARvtENkMTU1  ，然后翻到上面找到讨论组
另外要确认你赞助的不是游戏金币之类的
