### ISSUE TITLE
希望增加返回快捷键

### ISSUE THREAD

**Issue by smhxdtx** [niuhuan/jasmine#14]
jasmine、pikapika、nhentai-cross增加返回快捷键，就可以用鼠标侧键快速返回了

**Comment by niuhuan** [comment]
我本来希望使用右键可以返回的, 不过flutter不支持, 你希望的是加到哪个页面, 还是说像苹果的轨迹球一样?

**Comment by smhxdtx** [comment]
我希望加到开始阅读页面和漫画阅读结束时的页面
