### ISSUE TITLE
jm168版本无法登录，已一月有余

### ISSUE THREAD

**Issue by jockey470** [niuhuan/jasmine#152]
![image](https://github.com/user-attachments/assets/5df3c61a-7aea-4a9d-a39d-82f65ad8ede5)

**Comment by jockey470** [comment]
全局代理不行，图片分流全是失败，没有速度

**Comment by jockey470** [comment]
兄弟们，换全局直连可以登录

**Comment by jockey470** [comment]
刚好试了用全局直连可以，全局代理不行，谢谢，已经解决了> 今天测试，可以登录正常使用。网络问题需要自行解决。
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/2219ec2f-6264-474f-9f5f-c45d0cd7fb8e)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/2c14bf04-da33-4d8f-8e96-687021f60761)
> 
> 
> 
>

**Comment by hyyx233** [comment]
我是清除全部数据之后就算不挂梯子也可以登陆进去正常加载图片，但是一关掉再打开就说初始化失败请设置网络怎么都进不去，挂梯子全局还是直连都不行，就一定得清除全部数据用登陆的方式才进的去

**Comment by Yangleis** [comment]
和网络没有关系，应用信息-清空数据，就好了。
或者卸载重装。
