### ISSUE TITLE
网络没问题就是进不去

### ISSUE THREAD

**Issue by hyyx233** [niuhuan/jasmine#155]
如图所示，挂着梯子都没用
![QQ截图20241001180532](https://github.com/user-attachments/assets/10f4d8da-4258-44e6-84b5-f7a1a502c456)
![QQ截图20241001180543](https://github.com/user-attachments/assets/2f929e2c-cef3-4a2f-8944-e97f91bcc935)
![QQ截图20241001180553](https://github.com/user-attachments/assets/402e921c-0c6d-492a-bcb9-08a75458cec1)

**Comment by ajntm666** [comment]
jm1.6.9无法登录
![Screenshot_2024_1009_173455](https://github.com/user-attachments/assets/823a86a4-0f6b-40ef-8560-d9edce704281)
