### ISSUE TITLE
源码不提供后端核心代码是有意为之吗？

### ISSUE THREAD

**Issue by lanyeeee** [niuhuan/jasmine#157]
关于这个问题 #156 ，我今早抓包发现是因为jm的API域名改了，所以想提交一个PR

我简单浏览了[jasmine](https://github.com/niuhuan/jasmine)的源码，发现源码只有前端的部分，没有后端的rust实现

我注意到你的另一个项目[jenny](https://github.com/niuhuan/jenny)提供了后端的rust实现，如果我想给jenny提交PR，我大概只需要修改[这部分](https://github.com/niuhuan/jenny/blob/3598aaf1d051b95e57ee977e4bfc6d2cc5c22d42/native/jmcomic-rs/src/entities.rs#L389-L394)即可，不过你已经从jenny迁移到这里了，所以我没这么做

[jasmine](https://github.com/niuhuan/jasmine)为什么不像[jenny](https://github.com/niuhuan/jenny)那样提供后端的代码呢？

**Comment by niuhuan** [comment]
是有意而为之，jasmine完全可用时，将代码克隆出来一份，删掉了发电（赞助）部分的代码，形成了新的仓库jenny。
主要是jasmine赞助部分有单独的公私密钥，我不想别人拿来直接改完就能接受赞助发电。

**Comment by niuhuan** [comment]
感谢您的提议，我会抽时间重新抓包一下官方客户端。

**Comment by lanyeeee** [comment]
感谢解答
另外这是我今早抓到的，移动端的API域名，希望能帮到你
```
https://www.cdnxxx-proxy.xyz
https://www.cdnxxx-proxy.co
https://www.cdnxxx-proxy.vip
https://www.cdnxxx-proxy.org
```

**Comment by niuhuan** [comment]
十分感谢。后期会考虑能刷新从git仓库获取地址，而不是写死在代码里。

flutter更新很快，我不得不反复切换flutter版本来开发不同的项目。以致jm的迭代越来越慢。

**Comment by niuhuan** [comment]
您使用什么工具对app抓包呢？我试了几个手机端工具（Stream(iOS)/HttpCanary(android)）都没办法成功抓取

**Comment by lanyeeee** [comment]
mumu模拟器，模拟器里装 Reqable 和 官方jm app
# 1. mumu 模拟器开启 `root 权限` 和 `可写系统盘`
![image](https://github.com/user-attachments/assets/d0dd6489-bd7f-4b0e-864a-86005eac7c7b)
![image](https://github.com/user-attachments/assets/88ecb80a-23c1-4423-8657-fa26e8552911)

# 2. Reqable 安装证书
## 下载证书
![image](https://github.com/user-attachments/assets/66529e3d-5c9b-4dfc-8eec-e2be443050f4)
![image](https://github.com/user-attachments/assets/28bb80f5-f602-4d19-8cac-644dc7e5c180)
![image](https://github.com/user-attachments/assets/bbc9dd40-b160-40ad-9622-d61a98b10497)


把 下载到的证书放到模拟器的`/system/etc/security/cacerts`中，重启Reqable看到下面这样就是成功了
![image](https://github.com/user-attachments/assets/a790bf94-6f94-4d11-b796-91385d1c0e65)
# 3. 抓包
![image](https://github.com/user-attachments/assets/c26f8da0-542f-40aa-9d08-c44d1e395d93)
![image](https://github.com/user-attachments/assets/906a1c24-6cd2-4729-9f97-93af4194b2c5)
![image](https://github.com/user-attachments/assets/39606c86-9fc5-4c40-8214-5a7af090b319)
![image](https://github.com/user-attachments/assets/3dafa9da-bfc8-419e-85ec-c324118237bc)
![image](https://github.com/user-attachments/assets/f0cc267c-31a7-4e7f-bfb4-90e2fe0a8436)
然后打开模拟器里的jm app就行了
![image](https://github.com/user-attachments/assets/0b99b3ee-5893-4c46-9d00-951dc823feb0)
