### ISSUE TITLE
版本号问题

### ISSUE THREAD

**Issue by saltglow** [niuhuan/jasmine#158]
您发布了1.6.10版本。而arm64安装包的版本号实际上是1.7.0

很好奇这个问题产生的机制，于是提了上来，望解惑。

鄙人认为这是再小不过的问题，是出于学习目的提交的议题。

**Comment by niuhuan** [comment]
忘记改了 它没有提示更新就好了

**Comment by saltglow** [comment]
谢谢解答,我还以为是编译时意外产生的错误.
