### ISSUE TITLE
网页内能看，但APP内加载中卡死

### ISSUE THREAD

**Issue by CarlLester** [niuhuan/jasmine#16]
![Screenshot_20220324_112412](https://user-images.githubusercontent.com/16029615/159836023-55bdf4d5-aa23-4a44-be87-5bf3b2ad2aa5.jpg)
![Screenshot_20220324_112431](https://user-images.githubusercontent.com/16029615/159836031-a0d67d56-3a0f-409b-ad7a-d91524aa6bb7.jpg)

比如很多漫画123456789话，中间3579话不能看，点进去就是加载中，但网页版能看。

这个bug比较影响体验。

**Comment by niuhuan** [comment]
应该是官方api不标准, 返回了什么稀奇古怪的内容, 初步预测兼容一下就可以了。

需要提供漫画的名字, 或者怎么能搜索到。

**Comment by niuhuan** [comment]
![Screenshot_20220325-163007_VNC Viewer](https://user-images.githubusercontent.com/20847533/160083743-88681a2f-f0ce-4bd5-999f-95ad2a1db90e.png)

这个漫画所有的章节都能看，没发现什么问题。
