### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Jinlingsang** [niuhuan/jasmine#163]
为什么登不上去，一直提示这个!![image](https://github.com/user-attachments/assets/7d418b39-eb43-4460-994e-1a5ddc5e2024)

**Comment by a386756075** [comment]
好像是分流地址不一样了

**Comment by Jinlingsang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Jinlingsang** [comment]
> 好像是分流地址不一样了

你知道怎么解决吗

**Comment by niuhuan** [comment]
切一下分流

**Comment by Jinlingsang** [comment]
> 分流

之前试过了。那我再去试试看

**Comment by Jinlingsang** [comment]
> 切一下分流

之前试过了。那我再去试试看

**Comment by Jinlingsang** [comment]
> 切一下分流

还是不行~分流都切了一遍。直连也不行😂

**Comment by Jinlingsang** [comment]
> 切一下分流
切了分流。改了全局代理。换了新加坡的线路
![image](https://github.com/user-attachments/assets/666a65da-335e-4276-a9ec-e1ad0e028035)![image](https://github.com/user-attachments/assets/ab0dddc4-e53c-49d6-b268-8176c383baf2)

**Comment by a386756075** [comment]
分流地址变了，1.6.10是18comic–god.*，官方是18comic-idv.*和18comic-dov.*

**Comment by Jinlingsang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
