### ISSUE TITLE
漫画目录排序有问题

### ISSUE THREAD

**Issue by LuoChaoIOS** [niuhuan/jasmine#17]
漫画阅读界面目录排序错乱，会出现 1、10、100、101、102、11、12、13.......2、20、21、22、23......3、30、31 这样的排序

**Comment by niuhuan** [comment]
原版漫画没有错乱吗

**Comment by LuoChaoIOS** [comment]
我看了网页版目录并没有乱序。
出现乱序的漫画：例如-韩漫 《美麗新世界》
1、详情页目录偶现乱序
2、阅读页目录必定乱序

**Comment by niuhuan** [comment]
👌

**Comment by LuoChaoIOS** [comment]
最新版本该问题已经修复了，辛苦了
