### ISSUE TITLE
作者能不能把更新移动到右上角，64位的，这样看着有点不美观

### ISSUE THREAD

**Issue by lpq147258** [niuhuan/jasmine#18]

**Comment by lpq147258** [comment]
![Uploading Screenshot_2022-03-30-02-01-23-284_niuhuan.jasmine.jpg…]()

**Comment by niuhuan** [comment]
你图片没传完

**Comment by lpq147258** [comment]
> 你图片没传完

![Uploading Screenshot_2022-03-30-04-27-51-823_niuhuan.jasmine.jpg…]()

**Comment by lpq147258** [comment]
![Uploading Screenshot_2022-03-30-04-27-51-823_niuhuan.jasmine.jpg…]()

**Comment by lpq147258** [comment]
![Screenshot_2022-03-30-04-27-51-823_niuhuan jasmine](https://user-images.githubusercontent.com/93760738/160701929-e5c5ebb1-719c-4874-a112-6c367b7dca46.jpg)
![Uploading IMG_20220330_043421.jpg…]()

**Comment by lpq147258** [comment]
> 你图片没传完

![Uploading IMG_20220330_043421.jpg…]()

**Comment by lpq147258** [comment]
![Uploading IMG_20220330_043421.jpg…]()

**Comment by lpq147258** [comment]
> 你图片没传完

![Uploading IMG_20220330_043421.jpg…]()

**Comment by lpq147258** [comment]
![IMG_20220330_043421](https://user-images.githubusercontent.com/93760738/160702491-3154cf67-265a-482b-a931-47cc36e311e2.jpg)

**Comment by niuhuan** [comment]
你是说像pikapika一样？

**Comment by lpq147258** [comment]
是的，

**Comment by niuhuan** [comment]
貌似更新出了问题，就算更新到最新版，提示一直在

**Comment by niuhuan** [comment]
#22 已合并
