### ISSUE TITLE
软件功能计划 & BUGS & 参与项目(PR)

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/jasmine#2]
下载到本地功能制作中

- [x] 浏览记录
- [x] 下载漫画 / 本地收藏
- [x] 卡片模式下列的选择
- [x] 卡片模式下标题文字的展示
- [x] 流式模式下显示总数
- [ ] 游戏
- [x] 使用键盘翻页
- [x] 下载导出
- [x] 安卓120fps支持
- [x] 主题切换
- [x] 评论区
- [x] 主题切换

修复BUG列表 :

- [x] 点击继续阅读, 不能正确定位到上次的图片，只有单个章节的漫画才有这个BUG (flutter)
- [x] 手机端收藏不能翻页, 手机太长时出现, 电脑端无此BUG (flutter)

可PR内容:

PR前可使用discord或者在issue下留言联系作者, 或者从apk中取得.so文件。
- [ ] 主题美化

**Comment by lpq147258** [comment]
希望加一个和原版一样的列表，就是封面模式弄成双列，漫画名也显示出来

**Comment by niuhuan** [comment]
1

**Comment by lpq147258** [comment]
希加入原版的各种分类

**Comment by niuhuan** [comment]
那是个啥

**Comment by lpq147258** [comment]
打开禁漫不是有个分类吗，比如全彩，同人，纯爱，3D这些

**Comment by niuhuan** [comment]
首页横向的滚动条就是啊

**Comment by Minori-ty** [comment]
希望增加一个漫画的total总页，像哔咔那样可以知道当前的页数与总页

**Comment by Minori-ty** [comment]
rust和go，哪个好用？

**Comment by niuhuan** [comment]
> rust和go，哪个好用？

都很不错, 无法比较。

go比较容易上手, rust学起来比较困难。

**Comment by GustabMG** [comment]
翻页好困难啊，作者没想过添加用空格键翻页什么的吗？

**Comment by niuhuan** [comment]
上下键和空格, 你看怎么样。

**Comment by Minori-ty** [comment]
我有个想法，为什么你的输入框都这么突兀？和别的软件不太一样![Screenshot_2022-01-25-22-28-53-377_niuhuan.jasmine.jpg](https://user-images.githubusercontent.com/79521943/150995841-2e55f209-5a00-4548-aaec-6b0a05756e47.jpg)

**Comment by xushet** [comment]
希望能增加无需登录的本地收藏，以及上次浏览位置，现在是浏览时返回到详情页再继续浏览就又重头开始看了

**Comment by niuhuan** [comment]
> 希望能增加无需登录的本地收藏，以及上次浏览位置，现在是浏览时返回到详情页再继续浏览就又重头开始看了

可以继续阅读的，但是必须点击继续阅读按钮，而且不是第三种阅读器模式

**Comment by niuhuan** [comment]
@xushet  图中的继续阅读按钮就是

![Screenshot_20220131-162046](https://user-images.githubusercontent.com/20847533/151760360-3cef3cbf-53fc-4f30-bcfb-68e1a877804a.jpg)

**Comment by niuhuan** [comment]
本地收藏和下载功能, 估计一个月以内?

![WX20220214-134248](https://user-images.githubusercontent.com/20847533/153806793-c4d94de0-04e7-4be9-8260-525366eac916.png)

**Comment by ACGN520** [comment]
![Screenshot_20220620_090852.jpg](https://user-images.githubusercontent.com/72953635/174508556-1f344651-1217-43ae-929d-c872b8e3602c.jpg) 希望封面可以支持漫画类型显示

**Comment by Minori-ty** [comment]
搜索记录可以做成像b站那样长按删除吗？

**Comment by Minori-ty** [comment]
首页加载的时候是刷一下才出现的，有点突兀，可以添加一个骨架屏作为占位

**Comment by Minori-ty** [comment]
大哥，我要开始学习开发安卓了，是推荐flutter？还是kotlin的compose？

**Comment by niuhuan** [comment]
> 大哥，我要开始学习开发安卓了，是推荐flutter？还是kotlin的compose？

Compose库会比较少。而且不知道是不是支持ios。

**Comment by Minori-ty** [comment]
> > 大哥，我要开始学习开发安卓了，是推荐flutter？还是kotlin的compose？
> 
> Compose库会比较少。而且不知道是不是支持ios。

应该不支持ios，就是单纯的做安卓开发
