### ISSUE TITLE
github怎么使用？

### ISSUE THREAD

**Issue by 3225190360** [niuhuan/jasmine#24]

**Comment by 3225190360** [comment]
iOS移动版怎么把APP下载到手机上呢？

**Comment by niuhuan** [comment]
搜索已经关闭的issues可以找到答案

**Comment by 3225190360** [comment]
> 搜索已经关闭的issues可以找到答案
第一次用github，还是不懂怎么办

**Comment by niuhuan** [comment]
> > 搜索已经关闭的issues可以找到答案
> > 第一次用github，还是不懂怎么办

先下载ipa, 然后搜索一下怎么安装ipa, 自签名, altStore, i4助手之类的关键字。

**Comment by 3225190360** [comment]
> > > 搜索已经关闭的issues可以找到答案
> 
> > > 第一次用github，还是不懂怎么办
> 
> 
> 
> 先下载ipa, 然后搜索一下怎么安装ipa, 自签名, altStore, i4助手之类的关键字。
> 
> 

ipa怎么下载嘞，不会唉

**Comment by niuhuan** [comment]
项目首页找ipa

**Comment by 3225190360** [comment]
> 项目首页找releases

下载了，但是我的iOS版本是15.2.1的，好像不能越狱

**Comment by niuhuan** [comment]
> > 项目首页找releases
> 
> 下载了，但是我的iOS版本是15.2.1的，好像不能越狱

关于IPA的技术我并不专业，您需要多借助搜索引擎。不管手机越狱与否，您都需要先签名再安装。
