### ISSUE TITLE
<bug反馈>无法删除已下载的漫画，且无法重新加载下载失败的页

### ISSUE THREAD

**Issue by HIAMJ** [niuhuan/jasmine#25]
如题

**Comment by niuhuan** [comment]
建议你长按下载试一下

**Comment by niuhuan** [comment]
我记得长按可以删除

**Comment by niuhuan** [comment]
好吧。设计的时候，如果下载失败了，下次进入应用会继续下载。

**Comment by HIAMJ** [comment]
我还在使用您的另一款软件pikapika，在pikapika上这些功能都是正常的

**Comment by HIAMJ** [comment]
非常感谢您开发的第三方软件，禁漫天堂的这个客户端依旧是我使用过最好的第三方客户端，如果能修复一下这些小bug就更好了

**Comment by niuhuan** [comment]
> 另外有一个相对恶性的bug，如果在下载开始时因为网络原因请求失败，下载无法结束也没办法重新开始，在漫画详情页面显示了已经下载了，下载管理页面因为无法删除，又没有办法重新下载，只能卸载软件重新安装才能解决

重新打开软件不可以继续下载吗？

**Comment by HIAMJ** [comment]
大部分时间这个功能不生效

**Comment by niuhuan** [comment]
> 大部分时间这个功能不生效

可以尝试kill掉软件再打开，如果不行的话，那应该没有办法了。后期可以像pika一样设置一个手动renew的按钮。

**Comment by HIAMJ** [comment]
这种基本的操作已经尝试过，这个进入软件重新下载的功能基本都无法生效

**Comment by HIAMJ** [comment]
期待您后续版本的更新，感谢

**Comment by kevinxluo** [comment]
作者老哥，我也出现这个问题了，设备是iPhone11，ios13.1.3。这应该是一个共性问题

**Comment by niuhuan** [comment]
@HIAMJ  @kevinxluo  应该是换电脑的时候电脑丢了一部分,  还加了一个手动重新下载的按钮, 但是我没有测试, 最近肝不是很够用。

**Comment by kevinxluo** [comment]
> @HIAMJ @kevinxluo 应该是换电脑的时候电脑丢了一部分, 还加了一个手动重新下载的按钮, 但是我没有测试, 最近肝不是很够用。

老哥慢慢来，您的工具非常好用，等空闲时候再修复就好

**Comment by niuhuan** [comment]
> > @HIAMJ @kevinxluo 应该是换电脑的时候电脑丢了一部分, 还加了一个手动重新下载的按钮, 但是我没有测试, 最近肝不是很够用。
> 
> 老哥慢慢来，您的工具非常好用，等空闲时候再修复就好

新的release已经修复了，您需要测一下
