### ISSUE TITLE
Android版無法使用，請修復

### ISSUE THREAD

**Issue by yzxjoe** [niuhuan/jasmine#28]
![9104E9C2-B8D4-41E5-A0A3-C16A03B60CFF](https://user-images.githubusercontent.com/5716973/167537667-9c30ce91-a8e3-4036-8fd2-21e3b6fe1d2e.png)
Android版無法使用（如圖），請修復

**Comment by niuhuan** [comment]
请您自行解决网络问题, 建议您调整设备的时间与标准时间一致。
