### ISSUE TITLE
需要windows客户端

### ISSUE THREAD

**Issue by GustabMG** [niuhuan/jasmine#3]
如题，我需要一个windows的客户端
并不会自己编译，希望作者能编译一个windows客户端。

**Comment by niuhuan** [comment]
windows 的客户端我有编译出来，但是存在卡顿，主要因为flutter在windows上Unique Pointer无法交由其他线程处理。卡顿表现为，加载图片时无法操作界面。

正在寻找方法。如果没有办法兼容。后期会为windows做个特殊兼容，前后端http通信解决这个问题, 请您耐心的等待。

**Comment by laoleyuan** [comment]
收到，感谢回复。期待中

**Comment by niuhuan** [comment]
你可以试试windows的好用不, 刚release了一个

**Comment by laoleyuan** [comment]
谢谢，我会试一下的
