### ISSUE TITLE
收藏夹无法使用

### ISSUE THREAD

**Issue by yzxjoe** [niuhuan/jasmine#30]
删除数据安装最新版后，收藏夹无法使用，测试了挂梯子与无梯子状态下，IOS与android端，问题依旧。使用官方APP没问题
 ![Snipaste_2022-05-21_14-30-30](https://user-images.githubusercontent.com/5716973/169639161-4fe1b519-e0b6-4032-be7a-45698c3bcea7.jpg)

**Comment by ericvlog** [comment]
我也一样的问题。

**Comment by niuhuan** [comment]
会尽快修复的

**Comment by niuhuan** [comment]
你们测试一下, 如果不能用的话就再反馈, 如果能用的话关闭issue

**Comment by yzxjoe** [comment]
分别测试了IOS和安卓端问题依旧，发现官方APP（IOS和Android）收藏也看不到了，网页版就没有问题

**Comment by niuhuan** [comment]
我在发布版本安卓arm64开发环境测试没有问题, 现在也不行了, 估计官方服务器抽风了吧, 明天再试试

**Comment by yzxjoe** [comment]
问题解决

**Comment by niuhuan** [comment]
啊
