### ISSUE TITLE
rust的使用仅仅只是CI/CD？

### ISSUE THREAD

**Issue by wenjiang** [niuhuan/jasmine#31]
我看了源码，rust似乎只是用于CI/CD。没有其他作用了

**Comment by niuhuan** [comment]
api部分，下载，数据库，缓存，这些也是用rust写的。为了防止和react项目一样被人做成收费项目，所以放在了私有仓库。如果您希望PR，可以使用DISCORD联系。如果您希望借鉴，可以参考Pansy项目，两个项目类似。您可以阅读GithubActions得知具体构建流程。

**Comment by wenjiang** [comment]
我已收到了。。。

**Comment by wenjiang** [comment]
我已收到了。。。
