### ISSUE TITLE
希望可以加入waifu2x功能，那就很完美了看漫画

### ISSUE THREAD

**Issue by HedioKojima** [niuhuan/jasmine#33]

**Comment by niuhuan** [comment]
手机端可以用waifu2x么，我对AI和Gpu计算并不了解？PC端或许可以使用命令行来完成。

**Comment by HedioKojima** [comment]
> 手机端可以用waifu2x么，我对AI和Gpu计算并不了解？PC端或许可以使用命令行来完成。

iOS 里有个 可达漫画 里面增强画质用的就是waifu2 但是需要自己导入漫画，每次都是需要慢慢下载，然后加入其中才可以舒服观看，有点费劲

**Comment by niuhuan** [comment]
我不知道怎么弄，我只找到了pc的命令行工具，没有找到相关的ios或者flutter项目

**Comment by alphavvv** [comment]
https://github.com/imxieyi/waifu2x-ios

**Comment by niuhuan** [comment]
> https://github.com/imxieyi/waifu2x-ios

怎么用

**Comment by Yao-DY** [comment]
偶然看到就贴一个安卓的waifu2x，这个作者的readme写的很细，应该能有所帮助
https://github.com/tumuyan/RealSR-NCNN-Android
