### ISSUE TITLE
似乎有未能及时删除缓存的BUG

### ISSUE THREAD

**Issue by Puiching-Memory** [niuhuan/jasmine#35]
描述：在手机上使用一段时间后，发现其占用空间远大于刚安装时，但并我没有选择”**下载**“来存储漫画，而只是单纯地浏览
环境：HarmonyOS 2.0.0.140 HUAWEI P10 Plus // jasmine v1.2.7
复现：使用系统自带软件“手机管家”->清理加速->应用->jasmine 查看软件占用总空间

PS：
根据观察，我发现在限制网速的情况下，查看新的漫画（未加载）时需要经历一段等待时间
而之前已经显示过的漫画再次查看则几乎无延迟（已加载 ！= 已下载）
所以我推测应用有一个缓存机制，但是没有设置上限

改进：提供一个应用内设置选项，可更改缓存上限，超限时根据文件日期取后者删除

Enjoy your day!🤣

**Comment by niuhuan** [comment]
没有容量上限。但是是有日期上限的，在菜单里面设置一下缓存超时日期。再次打开app会自动清理。

另外已下载的也会计算进去。

**Comment by niuhuan** [comment]
漫画信息以及章节缓存时间是2小时。超过则弃用

**Comment by Puiching-Memory** [comment]
感谢，我找到了那个清理按钮
我下意识地认为可调节的设置都在“个人中心”右上角的icon里面😥
