### ISSUE TITLE
mac 打开不了

### ISSUE THREAD

**Issue by exoticknight** [niuhuan/jasmine#36]
提示被玩坏了，要刷新也不知道哪里能刷新
提示发送请求错误，看地址是作者自己搞的服务器吧
surge 中地址也抓不到。如果地址不行能不能直接走正常网站的普通 http 请求，我自己开代理

**Comment by niuhuan** [comment]
可以试试科学上网

**Comment by niuhuan** [comment]
好像mac上并没有留下科学上网的入口, 您可以试试更换分流, 或者使用移动设备。

**Comment by exoticknight** [comment]
好吧
