### ISSUE TITLE
希望增加缩放功能，漫画字太小，需要放大才能看得见

### ISSUE THREAD

**Issue by Ren9527** [niuhuan/jasmine#37]

**Comment by ericvlog** [comment]
> 在漫画页面，选择界面类型，里面有可以缩放的类型。
> 
> 切换后，尝试双击，双指缩放等操作。

windows 版， 用中的缩放的类型 ，但下一张图片又变小，还有滑鼠滚动到下一张图可以优化速度一下吗？ 
谢谢

**Comment by niuhuan** [comment]
> > 在漫画页面，选择界面类型，里面有可以缩放的类型。
> > 切换后，尝试双击，双指缩放等操作。
> 
> windows 版， 用中的缩放的类型 ，但下一张图片又变小，还有滑鼠滚动到下一张图可以优化速度一下吗？ 谢谢

这个问题我一直没能解决, windows请使用双击放大的模式。🤔 我也记得不是很轻

**Comment by ericvlog** [comment]
假如可以，键盘移动向下，因为现在用滑鼠轮移动但很慢速度。
