### ISSUE TITLE
APP收藏目录好像有bug，不显示数据

### ISSUE THREAD

**Issue by NBXianYu** [niuhuan/jasmine#39]
1.APP收藏目录好像有bug，不显示数据。
2.下载列表-队列中的下载中，好像没得继续下载。
3.那个glxx集合版本的禁漫天堂登录好像有问题，登录不了。

**Comment by niuhuan** [comment]
刷新就是继续下载，

收藏夹确实没数据了。

glxx已经放弃了

**Comment by niuhuan** [comment]
收藏夹的问题会看一下
