### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [niuhuan/jasmine#4]
请问是否可以将应用发布到 F-Droid？

**Comment by niuhuan** [comment]
暂时没有计划发布到任何应用商店，也不希望他人发布到任何应用商店，软件使用了github-api进行软件更新自动检查。

1. 软件功能尚不完善，前后版本可互相覆盖
2. 我更在意开源社区的动态，对软件提出改进计划请使用issues

**Comment by linsui** [comment]
好的，明白了。谢谢！
