### ISSUE TITLE
为什么有很多没有资源但是有评论呢

### ISSUE THREAD

**Issue by guohr-226** [niuhuan/jasmine#40]
下载显示0/0
想问一下评论区的在哪里看到👀

**Comment by niuhuan** [comment]
下载显示0/0说明还没获取列表

**Comment by chaojiwu** [comment]
1.2.10版收藏夹内容显示不出     开发大大

**Comment by niuhuan** [comment]
> 1.2.10版收藏夹内容显示不出 开发大大

这只是个第三方客户端，这和版本没有关系，官方App的收藏夹也显示不出来
