### ISSUE TITLE
无法打开收藏夹

### ISSUE THREAD

**Issue by 12362566** [niuhuan/jasmine#41]
打开后是空的

**Comment by niuhuan** [comment]
官方APP收藏接口不返回收藏数据，我暂时没有改动。

**Comment by h304192** [comment]
官网和app都可以显示收藏夹，会不会是接口改了

**Comment by h304192** [comment]
> 官方APP收藏接口不返回收藏数据，我暂时没有改动。

官网和app都可以显示收藏夹，会不会是接口改了

**Comment by niuhuan** [comment]
> > 官方APP收藏接口不返回收藏数据，我暂时没有改动。
> 
> 官网和app都可以显示收藏夹，会不会是接口改了

我前两天下的app是不显示的
