### ISSUE TITLE
作品详情中，无法显示详情和分P

### ISSUE THREAD

**Issue by graytang** [niuhuan/jasmine#43]
翻了好几个作品，有的会有的不会，表面上看起来没有特定的规律
![Screenshot_20220813-103456_Pixel_启动器](https://user-images.githubusercontent.com/81507746/184465435-d2d36ffd-9068-4c41-974d-049cdc9333f8.png)

**Comment by niuhuan** [comment]
1

**Comment by niuhuan** [comment]
<img width="800" alt="QQ20220813-115029@2x" src="https://user-images.githubusercontent.com/20847533/184467380-3b49d4e5-5e6d-4b40-a382-17c1986025de.png">

我觉得可能是网络问题

**Comment by graytang** [comment]
确实是网络问题，抱歉🤣

**Comment by niuhuan** [comment]
没有刷新的按钮，好像不是很方便……😑

**Comment by graytang** [comment]
> 没有刷新的按钮，好像不是很方便……😑

在导航栏加一个？
