### ISSUE TITLE
[bug反馈]Android12 显示权限不足

### ISSUE THREAD

**Issue by HIAMJ** [niuhuan/jasmine#46]
![Screenshot_2022-08-30-21-35-44-85_5734e8eb49b4234](https://user-images.githubusercontent.com/50162569/187451554-d473b7c0-c038-47c6-9448-0aad0832e4df.jpg)
![Screenshot_2022-08-30-21-30-48-21_50a71b01b907706](https://user-images.githubusercontent.com/50162569/187451567-11aeccb9-1582-4d6f-9e0c-ad8f76329c14.jpg)
![Screenshot_2022-08-30-21-35-33-21_5734e8eb49b4234](https://user-images.githubusercontent.com/50162569/187451573-36d1aaf7-dbc3-4ce9-a3a2-3d12acf4547d.jpg)
![Screenshot_2022-08-30-21-35-37-60_50a71b01b907706](https://user-images.githubusercontent.com/50162569/187451578-fcbcbe84-f753-4532-9ca9-d10ca791920c.jpg)

**Comment by niuhuan** [comment]
从Download下面新建一个目录

**Comment by HIAMJ** [comment]
> 从Download下面新建一个目录

已解决，另有一个问题，导出的zip为什么去掉了后缀名，虽然可以批处理解决，但是不明白这样做的意义，导出模块能否将默认后缀名保留呢

**Comment by niuhuan** [comment]
> > 从Download下面新建一个目录
> 
> 已解决，另有一个问题，导出的zip为什么去掉了后缀名，虽然可以批处理解决，但是不明白这样做的意义，导出模块能否将默认后缀名保留呢

也有可能是个Bug，预期效果应该是有.zip结尾的，而且现在导出的文件还不能预览，也是个问题。

**Comment by niuhuan** [comment]
权限不足的问题下个版本会修复， 导出的文件拓展名没有问题， 您导出的时候选择zip、jmi， 最好仔细看一下
