### ISSUE TITLE
不太会用webdav

### ISSUE THREAD

**Issue by Lucifar13** [niuhuan/jasmine#48]
按照坚果云或者其他支持WebDAV的网盘设置了，点击同步url要么提示404，要么是bad state ……line 1 column 1。
这个url、用户名和密码都是网盘提供的，难道是只支持本地架设的WebDAV服务器？
麻烦大神劳心看完了。

**Comment by niuhuan** [comment]
需要一个文件的完整路径，认证使用了basic auth。只使用了。GET ， PUT。另外404的话，可能您需要手动创建上级文件夹。

TG群里有讨论，您也可以去群里问。

**Comment by Lucifar13** [comment]
意思是软件不能自动去备份吗？

**Comment by niuhuan** [comment]
> 意思是软件不能自动去备份吗？

在群里签到发电就可以打开自动备份了, 支持坚果云。
