### ISSUE TITLE
账号登陆问题

### ISSUE THREAD

**Issue by nichengge111** [niuhuan/jasmine#5]
如题，在禁漫官网可以顺利登陆，但是在软件中一直登陆失败，是什么原因呢？

**Comment by niuhuan** [comment]
我刚刚测试可以登录成功，用的4G网络。
可以尝试以下方法。

使用用户名而不是邮箱。
不同的网络环境。
密码中不要有特殊字

……等等。

**Comment by nichengge111** [comment]
感谢，已经解决
