### ISSUE TITLE
[Bug]安卓13闪退

### ISSUE THREAD

**Issue by Yao-DY** [niuhuan/jasmine#52]
版本1.3.6，安卓13（Color OS13）闪退，提示“由于未兼容当前的安卓系统封发生异常”，在更新1.3.6之前也就是1.3.5是可以正常打开的

**Comment by niuhuan** [comment]
好可怕 待我DEBUG一下

**Comment by niuhuan** [comment]
> 版本1.3.6，安卓13（Color OS13）闪退，提示“由于未兼容当前的安卓系统封发生异常”，在更新1.3.6之前也就是1.3.5是可以正常打开的

 多数手机应该用arm64， 可以先检查一下

**Comment by niuhuan** [comment]
我这里能正常运行, AVD Pixel2API33

**Comment by Yao-DY** [comment]
> > 版本1.3.6，安卓13（Color OS13）闪退，提示“由于未兼容当前的安卓系统封发生异常”，在更新1.3.6之前也就是1.3.5是可以正常打开的
> 
> 多数手机应该用arm64， 可以先检查一下

我下载的是arm64-v8a没错，但我这里会闪退 :(
