### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by ayanowii** [niuhuan/jasmine#53]
![Screenshot_20221014_210037_com huawei browser](https://user-images.githubusercontent.com/115798823/195855281-20d8786f-18d1-4a60-9e66-afa64e56cb04.jpg)
如图 登录时总显示已注册

**Comment by niuhuan** [comment]
您的邮箱可能收不到链接，尝试更换邮箱，或者您应该从邮箱里确认链接

**Comment by 872035804** [comment]
软件要怎么发电？
