### ISSUE TITLE
Android 12L闪退

### ISSUE THREAD

**Issue by ElementBridge** [niuhuan/jasmine#55]
![Screenshot_20221020-143127_设置.png](https://user-images.githubusercontent.com/63735260/196873182-e053685d-473e-49d7-9439-4da187798a5e.png)
老哥，最新版本jasmine-v1.3.6-android-arm64在安卓12L设备上闪退是咋回事啊

**Comment by niuhuan** [comment]
你有按照升级说明清除数据吗?

**Comment by ElementBridge** [comment]
> 你有按照升级说明清除数据吗?

抱歉抱歉，我眼瞎😂去data里备份了下数据，卸载重装可以了，麻烦老哥把issue关了吧。我的锅我的锅😂
