### ISSUE TITLE
win7 x64系统打开就崩，啥原因的呢？

### ISSUE THREAD

**Issue by Lucifar13** [niuhuan/jasmine#58]
有2台win7 x64的机子，不是ghost的，运行程序就停止工作，故障模块名称显示为：ucrtbase.dll，也不知道是缺了哪个运行环境，好像能装也都装了。

**Comment by niuhuan** [comment]
Flutter3 可能就不支持win7

**Comment by Lucifar13** [comment]
呃，好吧……
