### ISSUE TITLE
运行闪退

### ISSUE THREAD

**Issue by weiailuxueqi** [niuhuan/jasmine#6]
作者你好，我通过impactor将jasmine-v0.1.4-nosign.ipa打进iphone手机后，运行jasmine程序闪退。

**Comment by niuhuan** [comment]
已越狱的iphone8(ios12.4)使用正常。使用了免签名补丁（今天中午刚越狱的）

您需要确保您的ios设备使用arm架构64以上位元或以上的cpu，至少是iphone6，ios在11版本以上。

**Comment by niuhuan** [comment]
![20220208_124356](https://user-images.githubusercontent.com/20847533/152920414-6a16475d-c644-4cc7-bab8-e50fd2ea274e.jpg)
