### ISSUE TITLE
Cannot find 'migration_ffi' in scope

### ISSUE THREAD

**Issue by weiailuxueqi** [niuhuan/jasmine#63]
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/27498426/209421236-9af00f4d-94f0-4a75-bc18-9548bcabc725.png">
<img width="479" alt="image" src="https://user-images.githubusercontent.com/27498426/209421250-0c7e3b87-b28e-481d-be53-9963b319c41f.png">
代码：master最新代码

**Comment by weiailuxueqi** [comment]
请问这个”Cannot find 'migration_ffi' in scope“ 该如何处理？
之前用非M1芯片编译过老版本的代码，没有问题。

**Comment by 872035804** [comment]
软件要怎么发电？
