### ISSUE TITLE
发电不会，关于界面里面没有维护这个选项啊

### ISSUE THREAD

**Issue by bagakkkkkkkkk** [niuhuan/jasmine#65]
用了好多天都不会发电，求告知，关于里面没有维护选项啊呜呜呜
![Screenshot_2023-01-05-14-33-58-708_niuhuan jasmine](https://user-images.githubusercontent.com/122007587/210728284-612458ae-831d-45de-925f-8c0860448724.jpg)

**Comment by niuhuan** [comment]
在个人中心里面找闪电图标

**Comment by HYK-100** [comment]
没用啊

**Comment by HYK-100** [comment]
代码怎么搞
