### ISSUE TITLE
发不了电，点了没用啊，求爸爸们告诉咋发电谢谢

### ISSUE THREAD

**Issue by bagakkkkkkkkk** [niuhuan/jasmine#68]
发不了电，点了没用啊，求爸爸们告诉咋发电谢谢
![Screenshot_2023-01-13-22-36-04-277_niuhuan jasmine](https://user-images.githubusercontent.com/122007587/212345705-ca3eb282-1d04-4d6c-be39-dc231335d077.jpg)

**Comment by niuhuan** [comment]
加releases中的群和频道，签到白嫖
