### ISSUE TITLE
有没有电报群的链接？   

### ISSUE THREAD

**Issue by 872035804** [niuhuan/jasmine#70]
要如何发电？详细的

**Comment by niuhuan** [comment]
在这里已经提到了 https://github.com/niuhuan/jasmine/issues/69#issuecomment-1382655247

**Comment by 872035804** [comment]
> 在这里已经提到了 [#69（评论）](https://github.com/niuhuan/jasmine/issues/69#issuecomment-1382655247)
你说啥？

**Comment by 872035804** [comment]
> 在这里已经提到了 [#69（评论）](https://github.com/niuhuan/jasmine/issues/69#issuecomment-1382655247)

这个软件有网页版的吗？

**Comment by niuhuan** [comment]
没有

**Comment by 872035804** [comment]
> 有, 但是你需要自己学习使用

太多英文了，我看的脑瓜子疼

**Comment by 872035804** [comment]
> 有, 但是你需要自己学习使用

还有你为什么能回复我这么快？你是不是人机？

**Comment by niuhuan** [comment]
你是不是有毒

**Comment by 872035804** [comment]
> 你是不是有毒, 回得快也不行

哥，你贵姓啊？

**Comment by niuhuan** [comment]
> > 你是不是有毒, 回得快也不行
> 
> 哥，你贵姓啊？

没义务回答

**Comment by 872035804** [comment]
> > > 你是不是有毒, 回得快也不行
> > 
> > 
> > 哥，你贵姓啊？
> 
> 没义务回答

对了，哥  这发电怎么搞的

**Comment by niuhuan** [comment]
进群之后签到白嫖

**Comment by 872035804** [comment]
> 进群之后签到白嫖

电报群吗？

**Comment by 872035804** [comment]
有没有连接？

**Comment by 872035804** [comment]
> > 进群之后签到白嫖
> 
> 电报群吗？

有没有连接？

**Comment by niuhuan** [comment]
捐赠的话 afdian.net/@mmbot

**Comment by 872035804** [comment]
> 频道的话 https://t.me/+IyW4zJBHLDc4YTc9 捐赠的话 afdian.net/@mmbot

谢谢

**Comment by 872035804** [comment]
> > 频道的话 https://t.me/+IyW4zJBHLDc4YTc9 捐赠的话 afdian.net/@mmbot
> 
> 谢谢

哥   我能再请教你一个题吗？     注册电报群，我一直收不到验证码，你有没有办法解决？

**Comment by niuhuan** [comment]
国号+86, 加上你的手机号

**Comment by 872035804** [comment]
> 国号+86, 加上你的手机号

收不到验证码

**Comment by niuhuan** [comment]
> > 国号+86, 加上你的手机号
> 
> 收不到验证码  

不知道，我们一直能收到，你可以换个号试试

**Comment by 872035804** [comment]
> 

大哥，我进入电报群了，在哪里签到啊？
