### ISSUE TITLE
感谢作者，关于删除bug和改进建议

### ISSUE THREAD

**Issue by a545850326** [niuhuan/jasmine#72]
最后再次感谢作者的奉献
社会包括文明就是这么现实
创就会存在 就会有传承
前仆后继的传承就会形成共识 信仰 文化 文明 历史
从0到1总要有些人扛起来

bug反馈
无法删除bug 已经在安卓和win二个系统测试 
选择删除后 等待2个小时 还咋是在删除 刷新也没用。

添加下载失败bug
比如 一本漫画有5章节 已经下载3章。在选择下载另外两章实际不会下载的。

产品优化建议反馈
下载过程中会有些下载失败
具体表现显示一下子 图片数量0/0
希望可以加一个 从新下载的功能

多标签搜索
我尝试过 搜索两个以即上关键词 
实际搜索结果只显示第一个关键词，并且还会不准确显示一些别的结果。
尝试搜索格式   关键词 空格 关键词 

下次完成 单独一个文件夹显示就好了
下载很多漫画的都知道，下载过多后。
新下载项目 随机排序  要找很半天 
(或许是英文字幕循序排序 不确定)

**Comment by niuhuan** [comment]
感谢您打了这么多字，维护的时候我会对您提出的问题进行测试，如果付现，且比较简单会尽快加以修复。

下载增加分类选项或者搜索选项是个不错的想法。

**Comment by a545850326** [comment]
> 感谢您打了这么多字，维护的时候我会对您提出的问题进行测试，如果付现，且比较简单会尽快加以修复。
> 
> 下载增加分类选项或者搜索选项是个不错的想法。

谢谢
