### ISSUE TITLE
连接失败问题

### ISSUE THREAD

**Issue by DODOTAX** [niuhuan/jasmine#75]
小米10
安卓12 MIUI13.0.7
ROOT
重装过，但依然连接失败![Screenshot_2023-02-01-17-49-06-250_niuhuan.jasmine.jpg](https://user-images.githubusercontent.com/89824742/216009363-ca4bb446-7e70-4917-827b-6ecd9407b7a9.jpg)
安装时有报毒不知道是不是这个影响到了
![Screenshot_2023-02-01-17-55-52-234_com.miui.packageinstaller.jpg](https://user-images.githubusercontent.com/89824742/216010580-39662958-0898-48b6-aab3-b0fef49a853b.jpg)

**Comment by niuhuan** [comment]
您换个分流

**Comment by DODOTAX** [comment]
> 您换个分流

都试过了，不行

**Comment by niuhuan** [comment]
不要科学上网，分流3

**Comment by DODOTAX** [comment]
> 您换个分流

好吧，当我关闭代理时就能正常使用了

**Comment by DODOTAX** [comment]
> 不要科学上网，分流3

我测试了一下，只有台湾和大陆的节点可以访问，其他都不行🤔
