### ISSUE TITLE
a.gray.sexpay.m风险监测

### ISSUE THREAD

**Issue by 1290111521** [niuhuan/jasmine#76]
有没有可能能把这段特征码扣了去。
不扣也行，反正现在的系统加入白名单就可以。
咱就是想问问。
以前是不用加入白名单的，更新之后突然就开始监测了
今天开会的时候打开公司里带支付功能的客户端给大伙做演示，唰一下一个安全监测就来弹出来了，提示是色情内容，下边领导都乐了
太痛苦了

**Comment by niuhuan** [comment]
这不是代码的原因。软件的id被腾讯的应用库标记了。只能换个id。

这个项目还在美化种
github.com/niuhuan/jenny

**Comment by niuhuan** [comment]
这不是代码的原因。软件的id被腾讯的应用库标记了。只能换个id。从年前开始陆陆续续有软件被标记, 如果完全杜绝还是要换成港版Rom。

这个项目还在美化中
github.com/niuhuan/jenny
