### ISSUE TITLE
图片渲染的层被打乱

### ISSUE THREAD

**Issue by smAI42** [niuhuan/jasmine#77]
![Screenshot_20230208_054446](https://user-images.githubusercontent.com/70988460/217445195-685cac77-de12-44fa-8199-b794798acb26.jpg)
  
基本上所有本子都是这样显示，只有少数漫画正常。

**Comment by niuhuan** [comment]
我的另外一个仓库 Jenny 0.0.3尝试修复这个问题，正在构建。

**Comment by niuhuan** [comment]
已经修复好了
