### ISSUE TITLE
有关占用空间的疑问

### ISSUE THREAD

**Issue by gao-shi** [niuhuan/jasmine#8]
![Screenshot_2022-02-23-10-44-48-431_com miui securitycenter](https://user-images.githubusercontent.com/29992389/155253788-6f2d8e01-4e2c-4cd8-bb99-6647bca55fc4.jpg)
占用空间好多啊 捂脸

**Comment by niuhuan** [comment]
![Screenshot_20220223-113122](https://user-images.githubusercontent.com/20847533/155257490-001dead0-7249-4b66-81b5-26fac60cea90.jpg)

这一部分，包括了您下载的漫画，还有图片的缓存。

如果您看漫画比较频繁，您可以将自动清理改成一周。然后再重新打开软件。
