### ISSUE TITLE
【功能建议】两点功能建议

### ISSUE THREAD

**Issue by WangWenBin2017** [niuhuan/jasmine#80]
1. 希望支持在搜索框内输入JM号直接跳转或者能在搜索结果里面输出指定JM号的漫画，例如搜索框输入JM123456，直接进入JM123456漫画详情，或者在搜索结果直接呈现ID为JM123456的漫画供用户点击。
2. 希望优化iOS下的搜索框粘贴逻辑，iOS的复制粘贴菜单逻辑是双击，在打开搜索框之后，再关闭搜索框，有几率不会出现Paste菜单，需要多次双击，或者长按，有时候长按也不起作用。这一点在本app还好一些，pikapika情况更加严重，有时长按都不起作用，我猜测可能是框架的原因。
3. 上述内容基于latest版本的应用，系统版本为iOS 15.4.1，设备为iPhone 13 Pro。

**Comment by niuhuan** [comment]
1. 你只有搜JM12345才可以，（如果不行请用jenny，这个功能做过了，但是我不接的jasmine有没有），不存在的Id不行，而且JM大写。

2. App不是网页，默认所有文本不可选，除非您指出来您希望哪里是可选的，我才可以去改进。

3. 粘贴的逻辑没办法改进
