### ISSUE TITLE
安卓手机报毒，无法安装

### ISSUE THREAD

**Issue by Qiuyebai-1226** [niuhuan/jasmine#83]
![Screenshot_2023-02-20-11-13-09-89_d0f6572af797fe1d932039816ed9c9bc](https://user-images.githubusercontent.com/62199231/220001490-4b520f82-c286-464a-bcf2-61d0ae9b8818.jpg)
之前是可以正常安装使用的，但是一个月前突然开始报危险软件，现在无法安装，有办法处理下吗
手机是realme，版本是realme ui4.0

**Comment by niuhuan** [comment]
断网或者右上角的设置里修改，或者换jenny客户端
