### ISSUE TITLE
打不开软件

### ISSUE THREAD

**Issue by AETeliang** [niuhuan/jasmine#87]
下载完点进去会自动跳转到计算器界面

**Comment by niuhuan** [comment]
您可以在我的主页搜一下计算器

**Comment by AETeliang** [comment]
https://github.com/niuhuan/jasmine/assets/139647453/6d31e048-a7e1-4122-8f7a-cc5eb06cf313

主页搜不到呀

**Comment by AETeliang** [comment]
刚点进去闪了一下就变成计算器了

**Comment by niuhuan** [comment]
这个软件就是个计算机
