### ISSUE TITLE
安装时报错，iOS 14.4.1，已越狱并安装AppSync

### ISSUE THREAD

**Issue by Ahtaler** [niuhuan/jasmine#9]
https://imgur.com/a/LejRcqx
如图
（几乎是全平台应用，⭐️我投啦，巨佬！）

**Comment by niuhuan** [comment]
⊙∀⊙！

**Comment by niuhuan** [comment]
你用的这个工具是什么

**Comment by niuhuan** [comment]
用Sideloadly!, 签名方式选择 Ad-hoc

**Comment by JUDGEsir** [comment]
> 用Sideloadly!, 签名方式选择 Ad-hoc

带佬 ad-hoc一直报错Installation failed: 3892346881 ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.咋整

**Comment by niuhuan** [comment]
> Installation failed: 3892346881 ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.

你是不是没越狱。

**Comment by JUDGEsir** [comment]
> > Installation failed: 3892346881 ApplicationVerificationFailed (Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.
> 
> 你是不是没越狱。
ad-hoc签名方式是必须要越狱吗？。。 我第一次用这个
大佬能给我科普一下appleID和ad-hoc两种签名之间的区别吗？

**Comment by niuhuan** [comment]
越狱设备是让任何签名都能过, ipa是没签名过的, 所以越狱设备也不能用, ad-hoc是临时签。

**Comment by zxc6378800** [comment]
14.2.1（已越狱 也是安装错误 application is missing the application-idenentifier entitlement.

**Comment by niuhuan** [comment]
> 12mini 14.2.1（已越狱 也是安装错误 application is missing the application-idenentifier entitlement.

签名了吗？

**Comment by zxc6378800** [comment]
越狱了按道理不需要签名只要有ipa> 吗

**Comment by zxc6378800** [comment]
> > 12mini 14.2.1（已越狱 也是安装错误 application is missing the application-idenentifier entitlement.
> 
> 
> 
> 签名了吗？

>大哥 越狱机要什么签名 只要有ipa

**Comment by niuhuan** [comment]
> > > 12mini 14.2.1（已越狱 也是安装错误 application is missing the application-idenentifier entitlement.
> > 
> > 
> > 签名了吗？
> 
> > 大哥 越狱机要什么签名 只要有ipa

不签名没有 application-idenentifier

随便签一个名就能装了，比如用AltStore。

**Comment by niuhuan** [comment]
可以参考这个

https://github.com/niuhuan/pikapika/issues/124

**Comment by niuhuan** [comment]
此话题已经移动到 https://github.com/niuhuan/jasmine/issues/29
