### ISSUE TITLE
关于jasmine存储空间的消耗问题

### ISSUE THREAD

**Issue by thirstywatch** [niuhuan/jasmine#92]
系统：安卓9.0 
设备：华为mate9
在使用jasmine时内存空间被快速占用，且占用量很大。
![Screenshot_20230806_094043_com.android.settings.jpg](https://github.com/niuhuan/jasmine/assets/104352281/a49e16bf-ef73-4c1a-8d01-8795af0ab37c)

未找到jasmine根目录

**Comment by niuhuan** [comment]
菜单里有自动清空缓存的时间，可以手动清空，再或者可以删除一些下载。

**Comment by zujiaoyuzunb** [comment]
可以直接删掉
