### ISSUE TITLE
发了电显示未发电

### ISSUE THREAD

**Issue by 977729401** [niuhuan/jasmine#96]
发了电一直显示未发电，同步也没用

**Comment by niuhuan** [comment]
可以看一下最近的issue，其他人是发电成功的，您可以试一下全局代理之后点我曾经发过电几次，如果是success再输入我曾经发电码。

**Comment by 977729401** [comment]
> 可以看一下最近的问题，其他人发电是成功的，你可以试一下全局代理之后点我曾经发过电几次，如果成功再输入我曾经发电码。

发电代码怎么看呢

**Comment by niuhuan** [comment]
群里签到，或者其他渠道取得的100位密码

**Comment by hugolubingshen** [comment]
弱弱的问一句，发电有什么用？

**Comment by niuhuan** [comment]
不知道的话就是没用

**Comment by 977729401** [comment]
按照网站上面的解决渠道进了电报群，电报群让进discord群，进了discord群问问题没人回，这也怪我咯。您回答的进群签到或者其他渠道获得的100位密码，我想问问进群签到是进哪个群？其他渠道是什么渠道？为什么花了钱还要用其他渠道获得本应该有的功能？问下支付订单号核对一下就解决的事情，非要搞那么复杂。完了还阴阳一句，我每个渠道都尝试过了，想问问你们又做过哪些售后？如果有解决方法，我希望你们将所有方法罗列出来公示，而不是敷衍回答用户的问题，如果花钱不能获得任何体验提升，那我也希望你们公示出来




夜希辰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "niuhuan/jasmine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [niuhuan/jasmine] 发了电显示未发电 (Issue #96)





 
不知道的话就是没用

**Comment by niuhuan** [comment]
> 按照网站上面的解决渠道进了电报群，电报群让进discord群，进了discord群问问题没人回，这也怪我咯。您回答的进群签到或者其他渠道获得的100位密码，我想问问进群签到是进哪个群？其他渠道是什么渠道？为什么花了钱还要用其他渠道获得本应该有的功能？问下支付订单号核对一下就解决的事情，非要搞那么复杂。完了还阴阳一句，我每个渠道都尝试过了，想问问你们又做过哪些售后？如果有解决方法，我希望你们将所有方法罗列出来公示，而不是敷衍回答用户的问题，如果花钱不能获得任何体验提升，那我也希望你们公示出来
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 夜希辰
> 
> ***@***.***
> 
> 
> 
> 
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "niuhuan/jasmine"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2023年10月30日(星期一) 下午5:00
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [niuhuan/jasmine] 发了电显示未发电 (Issue #96)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 不知道的话就是没用
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你加的不是我们第三方app群。你加的是官方群，官方的App不需要发电。

而且发电就是没什么用。

**Comment by niuhuan** [comment]
你去别人群里问我们的软件当然不会有结果。😀ོ
