### ISSUE TITLE
更新完打开是计算机怎么办

### ISSUE THREAD

**Issue by w57kt8** [niuhuan/jasmine#97]
更新完打开是计算机怎么办

**Comment by Barrykjj** [comment]
我记得是输入几个数字，在下载界面有，类似于app密码这种



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月7日(周六) 凌晨1:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [niuhuan/jasmine] 更新完打开是计算机怎么办 (Issue #97)




 
Closed #97 as completed.

**Comment by Barrykjj** [comment]
输入一段数字，选择版本界面有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月7日(周六) 凌晨1:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [niuhuan/jasmine] 更新完打开是计算机怎么办 (Issue #97)




 
Closed #97 as completed.
